### ISSUE TITLE
about training on kaggle dataset

### ISSUE THREAD

**Issue by lifecool** [thomasjhuang/deep-learning-for-document-dewarping#9]
Good day!;)
I try to train model on kaggle dataset, i use a train options from readme ... but get a error ... =(
create web directory ./checkpoints/kaggle/web...
Traceback (most recent call last):
  File "train.py", line 71, in <module>
    Variable(data['image']), Variable(data['feat']), infer=save_fake)
  File "/usr/local/lib/python3.6/dist-packages/torch/nn/modules/module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/torch/nn/parallel/data_parallel.py", line 153, in forward
    return self.module(*inputs[0], **kwargs[0])
  File "/usr/local/lib/python3.6/dist-packages/torch/nn/modules/module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/content/drive/Shared drives/UNLIMITED/ducunet/deep-learning-for-document-dewarping-master/models/pix2pixHD_model.py", line 163, in forward
    fake_image = self.netG.forward(input_concat)
  File "/content/drive/Shared drives/UNLIMITED/ducunet/deep-learning-for-document-dewarping-master/models/networks.py", line 180, in forward
    output_prev = model_upsample(model_downsample(input_i) + output_prev)
RuntimeError: The size of tensor a (398) must match the size of tensor b (400) at non-singleton dimension 2

How i can solve it?;)

**Comment by lifecool** [comment]
I solved it with cropping/scaling parameters. Good work!)

**Comment by thomasjhuang** [comment]
Sounds good, thanks!

**Comment by rishabh-vij** [comment]
hello @lifecool can you please let me know what value did you set the resize_or_crop parameter for training to work for you?

**Comment by sumanmichael** [comment]
@rishabh-vij, Pass this extra argument.

`python train.py [<YOUR OPTIONS>]   --resize_or_crop none`

**Comment by sumanmichael** [comment]
@rishabh-vij, this worked for me.

`python train.py [<YOUR OPTIONS>] --resize_or_crop none`
